### ISSUE TITLE
ossfs coredump with signal SIGSEGV with gdb stacktrace

### ISSUE THREAD

**Issue by rockeet** [aliyun/ossfs#162]
## 复现条件
多线程高压读写。
mount 命令：`gdb --args ossfs -f -ourl=http://oss-cn-shenzhen-internal.aliyuncs.com BucketName MountDir`

## 系统版本
```bash
$ uname -a
Linux iZwz92jc9tsm5e2lsktyzmZ 5.10.134-16.al8.x86_64 #1 SMP Thu Nov 16 05:08:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

$ md5sum /lib64/libfuse.so.2
29a2a1f8e046fda1c425c52cfe7155d3  /lib64/libfuse.so.2
```

## gdb stacktrace
```
Thread 1438 "ossfs" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff4e39640 (LWP 60274)]
check_parent_object_access (path=path@entry=0x0, mask=mask@entry=1) at s3fs.cpp:639
639     s3fs.cpp: No such file or directory.
(gdb) bt
#0  check_parent_object_access (path=path@entry=0x0, mask=mask@entry=1) at s3fs.cpp:639
#1  0x000000000040e09d in s3fs_flush (_path=<optimized out>, fi=0x7ffff4e38b10) at s3fs.cpp:2494
#2  0x00007ffff7f90744 in fuse_flush_common () from /lib64/libfuse.so.2
#3  0x00007ffff7f90af4 in fuse_lib_flush () from /lib64/libfuse.so.2
#4  0x00007ffff7f97936 in do_flush () from /lib64/libfuse.so.2
#5  0x00007ffff7f983f4 in fuse_ll_process_buf () from /lib64/libfuse.so.2
#6  0x00007ffff7f94ffd in fuse_do_work () from /lib64/libfuse.so.2
#7  0x00007ffff7d443fb in start_thread () from /lib64/libpthread.so.0
#8  0x00007ffff752be83 in clone () from /lib64/libc.so.6
```

**Comment by FangQianan** [comment]
Sorry for the late reply. 请问能提供一下更具体的复现步骤吗？仅凭这个堆栈看到s3fs_flush这个接口函数传进来的path参数变成空指针了，看起来像是libfuse传入的参数有些问题。我可以复现一下确认一下。

**Comment by FangQianan** [comment]
Sorry for the late reply. 请问能提供一下更具体的复现步骤吗？仅凭这个堆栈看到s3fs_flush这个接口函数传进来的path参数变成空指针了，看起来像是libfuse传入的参数有些问题。我可以复现一下确认一下。

**Comment by FangQianan** [comment]
> Sorry for the late reply. 请问能提供一下更具体的复现步骤吗？仅凭这个堆栈看到s3fs_flush这个接口函数传进来的path参数变成空指针了，看起来像是libfuse传入的参数有些问题。我可以复现一下确认一下。

@rockeet

**Comment by rockeet** [comment]
这个时间过去太久了，环境都没了 😓

**Comment by FangQianan** [comment]
我们发布了新版本1.91.9，新版本应该可以规避这个coredump。我们也会继续复现，也欢迎提comments。这个issue我先关闭了
